### ISSUE TITLE
Module refactoring

### ISSUE THREAD

**Issue by JanSnoh** [trulybeloved/Rekai#4]
# Description
Currently the code could use some amount of refactoring, to better split concerns and create an easier to follow data flow.

# Proposal
Here is a draft of what a better dataflow could look like 
![image](https://github.com/trulybeloved/Rekai/assets/31962956/f8f0929a-79ad-4fe3-a9e8-fe23cfdf58b5)

Which could imply a module call structure such as this
![image](https://github.com/trulybeloved/Rekai/assets/31962956/38d2ce51-e60c-478d-a7a2-c866ef1754ee)

## Notes
There is a lot of flexibility in the so called "HTML input type" (obviously just a placeholder name). 
Important considerations are:
* Contains Data about the all paragraphs and extra data
* Extra data needs to be nullable
* Keeps association between paragraphs and which data is associated with then
* Convenient to Iterate over.

Two suggestions:
1. It is entirely possible to do as part of the existing RekaiText data.
2. Another data structure to consider are dictionaries (or wrappers around them)

# Conclusion
By separating concerns in such a way you improve readability, minimize state (leading among other things to improved ease of debugging and testing), and improve modularity and reusability of bits of the code.

**Comment by JanSnoh** [comment]
Here the link to the referenced [sketches on Excalidraw](https://excalidraw.com/#json=TkiEqiW25zbzhX17zIumN,R1fwdZ-6NaoJszOW97wdDg).

**Comment by trulybeloved** [comment]
Thank you so much Jan! I redid the program outline to properly represent the present state and structure and I think I've grasped your perspective on this... will make appropriate changes and refactor over time...

**Comment by trulybeloved** [comment]
The refactor has been done accomplished for now. Thankyou so much Jan
